sudo: false
language: elixir
elixir:
  - 1.6
addons:
  postgresql: 9.6
cache:
  directories:
    - _build
    - deps
    - assets/node_modules
    - ~/.npm
env:
  - MIX_ENV=test
install:
  - mix do local.hex --force, local.rebar --force
  - mix do deps.get, compile, ecto.create, ecto.migrate
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - cd assets && npm install && cd -
before_script:
  - elixir --detached -e "File.write! 'pid', :os.getpid" -S mix phx.server
  - echo "starting phx server"
  - ./wait_script.sh # Should be one command instead, see here: https://stackoverflow.com/questions/49263953/why-is-bash-c-behaving-strangely
script:
  - mix format --check-formatted
  - mix coveralls.json
  - cd assets && $(npm bin)/cypress run && cd -
after_success:
  - if [ -f ./pid ];then;kill -9 "$(cat pid)";rm pid;fi
  - bash <(curl -s https://codecov.io/bash)
