sudo: false
language: elixir
elixir:
  - 1.7
addons:
  postgresql: 9.6
cache:
  directories:
    - _build
    - deps
    - assets/node_modules
env:
  global:
    - MIX_ENV=test
install:
  - mix do local.hex --force, local.rebar --force
  - mix do deps.get, compile --warnings-as-errors, ecto.create, ecto.migrate
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install -g elm@0.19.0 elm-test elm-format
  - (cd assets && npm install && npm run build)
script:
  - mix format --check-formatted
  - mix coveralls.json
  - elixir --detached -e "File.write! 'pid', :os.getpid" -S mix phx.server
  - echo "starting phx server"
  - |
    until $(curl --output /dev/null --silent --fail http://localhost:5001);do
      printf '.'
      sleep 5
    done
  - (cd assets && npm test)
  - kill -9 "$(cat pid)"
  - mix ecto.rollback --all
after_success:
  - bash <(curl -s https://codecov.io/bash)
