sudo: false
language: elixir
elixir:
  - 1.6
addons:
  postgresql: 9.6
cache:
  directories:
    - _build
    - deps
    - assets/node_modules
    - assets/elm-stuff/build-artifacts
    - sysconfcpus
    - ~/.npm
env:
  global:
    - MIX_ENV=test
    - ELM_VERSION=0.18.0
before_install:
  - # See: https://github.com/rtfeldman/node-test-runner/blob/master/.travis.yml
    if [ ! -d sysconfcpus/bin ];
    then
      git clone https://github.com/obmarg/libsysconfcpus.git;
      cd libsysconfcpus;
      ./configure --prefix=$TRAVIS_BUILD_DIR/sysconfcpus;
      make && make install;
      cd ..;
    fi
install:
  - mix do local.hex --force, local.rebar --force
  - mix do deps.get, compile, ecto.create, ecto.migrate
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install -g elm@$ELM_VERSION
  - mv $(npm config get prefix)/bin/elm-make $(npm config get prefix)/bin/elm-make-old
  - echo -e "#\!/bin/bash\\n\\necho \"Running elm-make with sysconfcpus -n 2\"\\n\\n$TRAVIS_BUILD_DIR/sysconfcpus/bin/sysconfcpus -n 2 elm-make-old \"\$@\"" > $(npm config get prefix)/bin/elm-make
  - chmod +x $(npm config get prefix)/bin/elm-make
  - cd assets && npm install && cd -
script:
  - mix format --check-formatted
  - mix coveralls.json
  - elixir --detached -e "File.write! 'pid', :os.getpid" -S mix phx.server
  - echo "starting phx server"
  - |
    until $(curl --output /dev/null --silent --fail http://localhost:4001);do
      printf '.'
      sleep 5
    done
  - cd assets && $(npm bin)/cypress run && cd -
  - kill -9 "$(cat pid)"
  - mix ecto.rollback --all
after_success:
  - if [ -f ./pid ];then;kill -9 "$(cat pid)";rm pid;fi
  - bash <(curl -s https://codecov.io/bash)
